version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        container_name: 77sol-app
        working_dir: /var/app/current
        volumes:
            - .:/var/app/current
            - /var/app/current/vendor
        networks:
            - laravel
        depends_on:
            - mysql
        ports:
            - "9000:9000"

    mysql:
        image: mysql:8.0
        container_name: 77sol-mysql
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: 77-sol
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - laravel
volumes:
    mysql_data:

networks:
    laravel:
